#!/bin/bash
# Just a shorthand to kill anything mongo running on the system. 
# Obviously not meant to be run on a production server. 
killall mongod
killall mongos
sleep 0.3
[ $(ps -ef|grep -c mongod) -gt 1 ] && killall -9 mongod
[ $(ps -ef|grep -c mongo) -gt 1 ] && killall -9 mongos
